default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: findMyCoffeeAPI_development

  test:
  <<: *default
  database: findMyCoffeeAPI_test

production:
  <<: *default
  database: findMyCoffeeAPI_production
  username: findMyCoffeeAPI
  password: <%= ENV['FINDMYCOFFEEAPI_DATABASE_PASSWORD'] %>
